apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-tjdp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-tjdp
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-tjdp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-tjdp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-tjdp
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-lhax-tenant/appstudio/dc-metro-map-tjdp@sha256:642a3b32b8fc14483e858b586161ba51055c16b41660ebe7a2de61c522ab2df5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
